# Generated by Django 6.0.4 on 2026-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shield', models.ImageField(upload_to='shields/')),
                ('team', models.ImageField(upload_to='teams/')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
